Initial site build
yghoor/Bootstrap-portfolio pull request #1
Opened 2022-03-16 10:12 UTC by yghoor

### Built bootstrap version of a portfolio site done according to spec from /curriculum-html-css/bootstrap-exercise.md

### Preview:
> **https://yghoor.github.io/Bootstrap-portfolio/**

Figma template - https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471

2022-03-22 10:43 UTC, Cerdtruir commented
Looks, good.

Im going to list the issues as i see them. 

The modal Github icon doesn't load.

I think the top portfolio item is supposed to change when scrolling over the lower ones in the grid. But thats not a big issue.

also the text over the grid portfolio items should change on hover. 

The form isnt expanding with the page like the figma template shows.

the form text box background should be grey

The button colors arent changing on hover and click



 But if there's no way to do some of these on bootstrap i dont think it matters.

2022-03-22 10:49 UTC, Cerdtruir commented on index.html
> +          <p class="col-9 col-sm-7 col-md-6 col-lg-5 col-xl-4 col-xxl-3 text-white">
It seems like you have lots of column changes, could you have used a percentage or something else?

2022-03-22 10:50 UTC, Cerdtruir commented on index.html
> +          <p class="col-9 col-sm-7 col-md-6 col-lg-5 col-xl-4 col-xxl-3 text-white">
There are a few others places i saw you did the same thing

2022-03-22 10:52 UTC, Cerdtruir requested changes
Please have a look at the other comments and fix the main issues. Otherwise it looks good

there also these error when loading the page: 

modal-icon-export.svg:1          Failed to load resource: the server responded with a status of 404 ()
modal-icon-github.svg:1          Failed to load resource: the server responded with a status of 404 ()
/favicon.ico:1          Failed to load resource: the server responded with a status of 404 ()

2022-03-23 13:12 UTC, yghoor commented
Necessary changes made

2022-03-23 13:36 UTC, Cerdtruir approved these changes

2022-03-23 13:38 UTC, merged